name: Print Message
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  run_code:
    name: Runs my code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: python longest.py
